version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    # For development
    # volumes:
    #   - ./pages:/app/pages
    #   - ./components:/app/components
    ports:
      - "3000:3000"